scheduler:
    _target_: custom_diffusers.continuous_ddpm.ContinuousDDPM
    beta_schedule: linear
    prediction_type: v_prediction
    clip_sample: false
    clip_range:
      - 4.5
      - 3.5
      
data_dir: /scratch/project_462001112/emulator_data/ 
save_dir: ./
guidance_scale: 2.0

# Seed for random number generators
seed: 42
variables: ["TREFHT"]
load_path: /projappl/project_462001112/CESM2_emulator_from_lumi/runs/run_test_aero_condenc_1708.pt
gen_mode: gen  # Either gen/val/test
batch_size: 8
sample_steps:  250
start_year: 1850
end_year: 2100
save_name: ssp370_aero # Only set a save name if you want something special added to your save path
samples_per: 10
cond_file: emissions_new.nc #emissions.nc
sul_mul: 0
co2_mul: 1
dataset:
  _target_: data.climate_datasetv2.ClimateDataset
  seq_len: 1

accelerator:
    mixed_precision: bf16

